baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo Blocks'

[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.116.0" # or whichever version you are using
