backend:
  name: git-gateway
  branch: master # Change this to your default branch

media_folder: "static/uploads" # Where media files are stored
public_folder: "/uploads"

collections:
  - name: "homepage"
    label: "Homepage"
    files:
      - label: "Homepage Content"
        name: "home"
        file: "content/_index.md"
        format: "frontmatter"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - label: "Blocks"
            name: "blocks"
            widget: "list"
            fields:
              - { label: "Type", name: "type", widget: "select", options: ["uno", "duo", "trio"] }
              - { label: "Title", name: "title", widget: "string" }
